name: flutter_scanner_plus
description: A plugin for barcode scanning support on Android and iOS. Supports barcodes, QR codes, etc.
version: 2.0.0
homepage: https://github.com/AlvaroVasconcelos/flutter_scanner_plus

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.6
  
dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.16.8

flutter:
  plugin:
    platforms:
      android:
        package: com.amolg.flutterbarcodescanner
        pluginClass: FlutterBarcodeScannerPlugin
      ios:
        pluginClass: SwiftFlutterBarcodeScannerPlugin